#!/usr/bin/expect

set timeout -1

## Lists the software that needs to be installed
set software " "

spawn arch-chroot [lindex $argv 0]

## Install software package
expect ":/# "
send "apt install -y $software \n"

expect ":/# "
send "exit\n"

interact
